module.exports = [
	{from: '/static/*', to:'/static/*'},
	{from: '/bootstrap/*', to:'/bootstrap/*'},
	{from: '/edit/*', to:'_show/edit/*'},
	{from: '/edit/', to:'_show/edit/'},
	{from: '/fork/*', to: '_show/edit/*', query: {fork:1}},
	{from: '/update_recipe', to: '_update/update_recipe'},
	{from: '/login', to: '_update/login'},
	{from: '/create_user', to: '_show/create_user'},
	{from: '/update_user', to: '_update/update_user'},
	{from: '/recipelist', to: '_list/recipelist/recipes_by_name'},
	{from: '/tags', to: '_list/testList/tags'},
	{from: '/tags/:key', to: '_list/testList/tags'},
	{from: '/recipe/*', to: '_show/recipeshow/*'},
	{from: '/search', to:'_show/search'},
	{from: '/', to: '_show/edit'},
	]
